//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelBasla.Excel {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Excel.IExcel")]
    public interface IExcel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExcel/GetData", ReplyAction="http://tempuri.org/IExcel/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExcel/GetData", ReplyAction="http://tempuri.org/IExcel/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExcel/Basla", ReplyAction="http://tempuri.org/IExcel/BaslaResponse")]
        byte[] Basla(string[] Baslik, System.Data.DataTable dataTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExcel/Basla", ReplyAction="http://tempuri.org/IExcel/BaslaResponse")]
        System.Threading.Tasks.Task<byte[]> BaslaAsync(string[] Baslik, System.Data.DataTable dataTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExcel/ExcelPivot", ReplyAction="http://tempuri.org/IExcel/ExcelPivotResponse")]
        byte[] ExcelPivot();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExcel/ExcelPivot", ReplyAction="http://tempuri.org/IExcel/ExcelPivotResponse")]
        System.Threading.Tasks.Task<byte[]> ExcelPivotAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExcelChannel : excelBasla.Excel.IExcel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExcelClient : System.ServiceModel.ClientBase<excelBasla.Excel.IExcel>, excelBasla.Excel.IExcel {
        
        public ExcelClient() {
        }
        
        public ExcelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExcelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExcelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExcelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public byte[] Basla(string[] Baslik, System.Data.DataTable dataTable) {
            return base.Channel.Basla(Baslik, dataTable);
        }
        
        public System.Threading.Tasks.Task<byte[]> BaslaAsync(string[] Baslik, System.Data.DataTable dataTable) {
            return base.Channel.BaslaAsync(Baslik, dataTable);
        }
        
        public byte[] ExcelPivot() {
            return base.Channel.ExcelPivot();
        }
        
        public System.Threading.Tasks.Task<byte[]> ExcelPivotAsync() {
            return base.Channel.ExcelPivotAsync();
        }
    }
}
